name: gestion_locative
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  http: ^1.6.0
  shared_preferences: ^2.5.3
  document_scanner_flutter:
    path: third_party/document_scanner_flutter
  image_picker: ^1.1.2
  file_picker: ^8.0.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.10
  url_launcher: ^6.3.0
  flutter_web_plugins:
    sdk: flutter
  feda_flutter: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo (2).png
    - assets/images/image1 (2).jpg
    - assets/images/img (2).jpg
    - assets/images/img.jpeg
