// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvU5twv8dFCpb-P95iO0Vju0tOAF2n9lw',
    appId: '1:392404840141:web:b1dcd12480f91d976b8384',
    messagingSenderId: '392404840141',
    projectId: 'gestion-loca-66598',
    authDomain: 'gestion-loca-66598.firebaseapp.com',
    storageBucket: 'gestion-loca-66598.firebasestorage.app',
    measurementId: 'G-9DMM4FK5XQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9YtN1FbsCsCb312LzE4LUr85RvzIQ6cg',
    appId: '1:392404840141:android:d1450f5a61c6f82e6b8384',
    messagingSenderId: '392404840141',
    projectId: 'gestion-loca-66598',
    storageBucket: 'gestion-loca-66598.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-6PUJ2ECHU4FSumA9TlmG3Z_rWM18zxE',
    appId: '1:392404840141:ios:86b9722d34779ad06b8384',
    messagingSenderId: '392404840141',
    projectId: 'gestion-loca-66598',
    storageBucket: 'gestion-loca-66598.firebasestorage.app',
    iosBundleId: 'com.example.gestionLocative',
  );
}
